services:
  database:
    image: 'bitnami/postgresql'
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=$DATABASE_USERNAME
      - POSTGRESQL_PASSWORD=$DATABASE_PASSWORD
      - POSTGRESQL_DATABASE=$DATABASE_NAME
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

volumes:
  postgresql_data:
    driver: local
